title: "Dr. Wilkistar Otieno"
author: "Dr. Wilkistar Otieno"
#description: "Open-Source, Internet, Krytopgraphie und anderes."
description: "Professor of Industrial Engineering, University of Wisconsin Milwaukee"
#subheading: "Open-Source, Internet, Krytopgraphie und anderes."
more: "zum Artikel"
#url: "http://niklabs.me"
url: "https://wilkistarotieno.github.io"

permalink: /:title/

paginate: 5

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/wilkistarotieno/"
  - twitter: "https://twitter.com"
  - google-plus: "https://plus.google.com"
  - reddit: "https://www.reddit.com"
  - youtube: "https://www.youtube.com"
  - steam: "http://steamcommunity.com"

markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "footnotes"]
excerpt_separator: "\n\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
